server:
  port: 8081

sindory:
  server:
    expire-second:  24

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sindory-aws.cnrt2iqjlblv.ap-northeast-2.rds.amazonaws.com:3306/work_env?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: yanolja1234

#  jpa:
    hibernate:
      ddl-auto: none
#       ddl-auto: update
#      ddl-auto: create-drop
    generate-ddl: true

    properties:
      hibernate:
        format_sql: true
        show_sql: true